# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
         AppBundle\Entity\User:
             algorithm: sha512
             encode_as_base64: true
             iterations: 5

    providers:
        my_provider:
           entity:
              class: AppBundle\Entity\User
              property: email

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login